FROM python:3.12-slim
WORKDIR /app
COPY backend/django-api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY backend/django-api /app
EXPOSE 8000
CMD ["gunicorn", "supportdesk.wsgi:application", "--bind", "0.0.0.0:8000"]
